### ISSUE TITLE
Improve the robots remaining checks

### ISSUE THREAD

**Issue by VinceBackpack** [cjlcarvalho/crazy-robots#18]
Increase performance of checking how many robots are left.

I would like to be assigned to this issue

**Comment by PopeSpaceous** [comment]
Here's some more information about the issue.
Currently the thereIsOneLastSurvivor() checks the size of the vector of robots. This function is called every iteration.
Since the function is calling a method that iterates through the vector, the function has a linear run-time (O(n)) I believe we can get it to a constant run-time (O(1)).
Implimentation: Having a global variable to keep track of the vector's size. Then compare that in the thereIsOneLastSurvivor() function. This would increase the performance of the program.

**Comment by cjlcarvalho** [comment]
As this program always will work with a number less or equal of four as the quantity of robots, I don't think that is necessary right now to be worried with the time complexity of vector::size() as N will be always <= 4.
